# ===================================
#  List Behavior Config
# ===================================

title: indikator.marketing::lang.menu.posts
list: ~/plugins/indikator/marketing/models/posts/columns.yaml

modelClass: Indikator\Marketing\Models\Posts
recordUrl: indikator/marketing/posts/update/:id
noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 15
showCheckboxes: true
showSetup: true

defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter: config_filter.yaml
